title: SapsanGit
syntax: Xml
supportedLanguages: []
properties: []
description: Руководство для сотрудников
style: blue
code: git
link:
  name: new-catalog
  pathname: "-/-/-/-/new-catalog"
  lastVisited: "-/-/-/-/new-catalog/new-article"
  logo: null
  title: Новый каталог
  query: {}
  group: null
  code: ""
  style: null
  description: null
  order: 999999
  isCloning: false
  cloneCancelDisabled: false
  redirectOnClone: null
relatedLinks: []
name: new-catalog
repositoryName: new-catalog
logo_dark: banner 100х100.png
